# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

PROB_3PLM <- function(theta, a, b, c, u, deriv) {
    .Call('ShadowCAT_PROB_3PLM', PACKAGE = 'ShadowCAT', theta, a, b, c, u, deriv)
}

PROB_GRM <- function(theta, a, b, u, deriv) {
    .Call('ShadowCAT_PROB_GRM', PACKAGE = 'ShadowCAT', theta, a, b, u, deriv)
}

PROB_SM <- function(theta, a, b, u, deriv) {
    .Call('ShadowCAT_PROB_SM', PACKAGE = 'ShadowCAT', theta, a, b, u, deriv)
}

PROB_GPCM <- function(theta, a, b, u, deriv) {
    .Call('ShadowCAT_PROB_GPCM', PACKAGE = 'ShadowCAT', theta, a, b, u, deriv)
}

